return PlaceObj('ModDef', {
	'title', "Fizzle Fuze's Library",
	'description', "Contains a bunch of stuff which my other mods use. Not meant to be used by itself.",
	'image', "Images/thumbnail.png",
	'last_changes', "https://github.com/Surviving-Mars-Mods/Fizzle_Fuze_Library/blob/master/changelog.md",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"src/*",
		"*.txt",
		"*.iml",
		".idea/*",
		"*.png",
	},
	'id', "FIZZLE1",
	'steam_id', "2755510871",
	'pops_desktop_uuid', "e24ba91b-0c3a-4374-973c-5bc9b2979a75",
	'pops_any_uuid', "0dff8bff-bbfb-4290-a19e-1af4e8799c24",
	'author', "Fizzle Fuze",
	'version_major', 1,
	'version_minor', 5,
	'version', 69,
	'lua_revision', 1009413,
	'saved_with_revision', 1010838,
	'code', {
		"Code/LibMain.lua",
		"Code/UI/TextStyles.lua",
		"Code/UI/XTemplates.lua",
	},
	'saved', 1645035305,
	'TagOther', true,
})